### ISSUE TITLE
Taxonomy ID Error

### ISSUE THREAD

**Issue by SuiyueWestlake** [BaderLab/EPIC#12]
I specified Taxonomy ID as 9606 (human), but there is an error "KeyError: '9606'“.
Then, I try to add link to line 659 in CalculateCoElutionScores.py, but I can not correctly get the link of human Taxonomy ID.
To overcome all these error, I generate gold standard protein complexes file myself, but when I don't specify -t, the error would be "KeyError: ''"
How can I fix these bugs?

**Comment by LucasHu** [comment]
Hi Siyue,

Thanks for using EPIC and let me know the problem. I suspect it is due to the dependent database changed its API. 

I noticed that the GO website also changed its API recently. I will need to update the EPIC source code. 

I will work on these issues the coming week, and will let you.

Sorry for the inconvenience.

Best
Lucas

**Comment by LucasHu** [comment]
Hi Siyue,

Sorry for my late reply. 

I was very busy last week and just got chance to look at the issue.

I installed EPIC onto my new laptop, and re-run EPIC on both worm and human data. It turns out to be running smoothly and no errors were reported. I tried both "pre-curated reference" and "asking EPIC to curate complexes reference", both are fine.

The following is the code I used. Could you give me more details about your problem? like what command line you tried, etc...

Best
Lucas

python /Users/zh2477/Desktop/EPIC/EPIC/src/main.py -s 11101001 /Users/zh2477/Desktop/EPIC/EPIC/test_data/RB/  -t 9606 /Users/zh2477/Downloads/ -M RF -n 6 -m EXP

**Comment by SuiyueWestlake** [comment]
Hi Lucas,

Thank you for your reply.

I also tried both "pre-curated reference" and "asking EPIC to curate complexes reference".

For "pre-curated reference" method, my command is 
python EPIC/src/main.py -s 11101001 /storage/lixuLab/suiyue/EPIC/InputFolder_TCR/ -t 9606 ./TCR_OutputFolder/ -o TCR -M RF -n 6 -m EX

But I got an error like 
File "/storage/lixuLab/suiyue/EPIC/temp/EPIC/src/CalculateCoElutionScores.py", line 666, in map_proteinNames
    response = urllib2.urlopen(taxoIDurl[self.taxoID])
KeyError: ''

For "asking EPIC to curate complexes reference", my command is 
python EPIC/src/main.py -s 11101001 /storage/lixuLab/suiyue/EPIC/InputFolder_TCR/ -c ./Human_coreComplexes.txt ./TCR_OutputFolder/ -o TCR -M RF -n 6 -m EX
The error is 
File "/home/lixuLab/suiyue/miniconda3/envs/epic2/lib/python2.7/httplib.py", line 700, in _safe_read
    raise IncompleteRead(''.join(s), amt)
httplib.IncompleteRead: IncompleteRead(6844 bytes read, 1348 more expected)
😭

Looking forward to your reply！

Best,
Yup

**Comment by LucasHu** [comment]
Hi Siyue,

The error is reported from calling external functional evidence, which you didn't use. 

Hmm, strange. Change your "-m EX" to "-m EXP". Will this solve your problem?

Best
Lucas

**Comment by SuiyueWestlake** [comment]
Hi Lucas,

EPIC runs smoothly now！ My command is
python EPIC/src/main.py -s 11101001 /storage/lixuLab/suiyue/EPIC/InputFolder_TCR/ -t 9606 ./TCR_OutputFolder/ -o TCR -M RF -n 6 -m EXP
Thank you so much！

In addition, I have another question. There are four files in test_data/elution_profiles. Are these four files related?
Since I only have one input file, which is a matrix, I suspect there is something wrong with my input file.

Best,
Yue

**Comment by LucasHu** [comment]
HI Siyue,

We have a simple analysis figure in my Nature Methods paper for how many co-frac experiments are needed, usually we changed the columns condition a bit, (i.e. changed to size exclusion, do pre-enrichment, etc…). I think one co-frac experiment is a bit too little, ideally four is recommended.

Hope this will help.

Best
Lucas

**Comment by SuiyueWestlake** [comment]
Thank you Lucas.
I will change the experiment strategy according to your suggestion.

Best,
Yue

**Comment by SuiyueWestlake** [comment]
Hi Lucas,

Thank you for your email!
EPIC is such a powerful tool that I would like to use it in my research.
Looking forward to your update!

Best,
SuiYue

发件人: LucasHuUofT ***@***.***>
日期: 星期日, 2022年7月17日 上午11:17
收件人: BaderLab/EPIC ***@***.***>
抄送: Yue SUI 岁月 ***@***.***>, Author ***@***.***>
主题: Re: [BaderLab/EPIC] Taxonomy ID Error (Issue #12)

Hi Siyue,

Thanks for using EPIC and let me know the problem. I suspect it is due to the dependent database changed its API.

I noticed that the GO website also changed its API recently. I will need to update the EPIC source code.

I will work on these issues the coming week, and will let you.

Sorry for the inconvenience.

Best
Lucas

―

**Comment by LucasHu** [comment]
Hi Suiyue,

I also already updated the code after last time you emailed me.

Please have a check.

Best
Lucas

**Comment by SuiyueWestlake** [comment]
Dear Lucas,

Thank you for telling me!

Best,
Yue
