### ISSUE TITLE
cytoscape visualization problem

### ISSUE THREAD

**Issue by smdb21** [BaderLab/EPIC#3]
Using the docker version of EPIC, I get it to run with my data, and it reaches the point in which is trying to build the visual representation of the clusters but I get the error:

ValueError: too many values to unpack

See capture here.
![image](https://user-images.githubusercontent.com/11353022/61555012-38780100-aa13-11e9-92ae-ea0544f16d1d.png)

In the output folder I already have these files:
- Out.rf.exp.clust.txt
- Out.rf.exp.pred.txt
- Out.rf.ref_complexes.txt
- Out.rf.scores.txt
I also can show you the log in the console that says: "Loaded graph with 3072 nodes and 72581 edges". 
![image](https://user-images.githubusercontent.com/11353022/61555200-a58b9680-aa13-11e9-917e-93632ac07b39.png)

PS: I had Cytoscape installed and running before starting EPIC.
Let me know if I can provide any more information.

**Comment by LucasHu** [comment]
hi Salvador,

I just tested EPIC that I can visualize predicted complexes in Cytoscape with no errors.

Could I see the first a few lines of 
Out.rf.exp.clust.txt
Out.rf.exp.pred.txt
Just wanna double check if the outputs from your EPIC are correct or not.

Meanwhile, since your EPIC run is already finished successfully before importing into Cytoscape. If you wanna visualize the results, you can always open Cytoscape and import results to visualize it.

best
Lucas

**Comment by smdb21** [comment]
[Out.rf.exp.pred.txt](https://github.com/BaderLab/EPIC/files/3412688/Out.rf.exp.pred.txt)
[Out.rf.exp.clust.txt](https://github.com/BaderLab/EPIC/files/3412689/Out.rf.exp.clust.txt)
Here are the entire final files

**Comment by LucasHu** [comment]
Hi Salvador,

I think I figured out the problem.

You have multiple contamination proteins in your input data, whose names are separated by “_”, this will create trouble.

For example, “contaminant_UBIQUITIN09"

Think you should remove those proteins before inputing into EPIC.

Tell me if this is working or not.

Best
Lucas

**Comment by smdb21** [comment]
Thank you! I will try to remove them.
Another problem I am having is that the step in which the proteins only present in 1 fraction are filtered out is not properly working with other input files.
An example file is attached here.
[test.txt](https://github.com/BaderLab/EPIC/files/3412907/test.txt)

If for one of the proteins I substitute a "0" by a "1" in two fractions, that protein passes the threshold. But it is somehow like not recognizing the values that are in the other columns. They are NSAF values.

**Comment by LucasHu** [comment]
Hi Salvador,

This is part of our EPIC workflow.

Due to the noisy nature of the co-fractionation data, we do some stringer filtration beforehand.
For example, if proteins are only detected in one fractions, they are filtered. Also for example, If the proteins are not detected in two nearby fractions, we filtered them out…

Best
Lucas

**Comment by smdb21** [comment]
I still not sure why the data is not read. 
I made sure now that every row in our input file corresponds to a protein with at least 2 consecutive non-NaN values.
You can see it in this example file with 50 lines:
[dSEC_NSAF_example.txt](https://github.com/BaderLab/EPIC/files/3418598/dSEC_NSAF_example.txt)
But still, I get this error:
![image](https://user-images.githubusercontent.com/11353022/61652623-3dd08800-ac6d-11e9-8892-27674cf6bebf.png)

**Comment by LucasHu** [comment]
Hi Salvador,

I looked at your file. 

It looks like the values are all extremely small, what is the reason?

EPIC is designed for raw spectral counts and MS1 intensity, so we set a cutoff at 1.

If your data is normalized somehow, you can multiply the raw value by 10^5 or ^6 to make sure they are bigger than 1. This works, since EPIC is calculating correlation scores and doing normalization automatically.


Best
Lucas

**Comment by smdb21** [comment]
Thanks for that! I think I already said that we were trying to use NSAF values, which usually are that small. We can transform the data and try again.
Thanks!
