### ISSUE TITLE
bio-epic: "Out.rf.exp.clust.txt"  can't be found

### ISSUE THREAD

**Issue by pizzaxx** [BaderLab/EPIC#6]
testing the docker vision of epic with the downloading data,The error jumped every time, before this step, all things are good. Can you help me handle this?

IOErrorTraceback (most recent call last)
<ipython-input-28-ccf9f16a664b> in <module>()
      2 # Evaluating predicted clusters
      3 pred_clusters = GS.Clusters(False)
----> 4 pred_clusters.read_file("%s.%s.clust.txt" % (output_dir, mode))
      5 out = utils.clustering_evaluation(all_gs.complexes, pred_clusters, "", True)

/home/jovyan/work/EPIC/src/GoldStandard.pyc in read_file(self, clusterF)
    737 
    738         def read_file(self, clusterF):
--> 739                 clusterFH = open(clusterF)
    740                 i = 0
    741                 all_proteins_count = 0

IOError: [Errno 2] No such file or directory: '/home/jovyan/work/input/Elution files_out/Out.rf.exp.clust.txt'

**Comment by LucasHu** [comment]
Hi, I have just tested the Docker version. It works well without reporting any errors.
Could you check the *_out file folder, did you see Out.rf.ref_complexes.txt file?

Best
Lucas

**Comment by pizzaxx** [comment]
Thank you for replying. I just checked my out file folder and the following files were what i had:
Out.rf.cutoff.pdf
Out.rf.exp.pred.txt
Out.rf.pr.pdf
Out.rf.ref_complexes.txt
Out.rf.roc.pdf
Out.rf.scores.txt

**Comment by LucasHu** [comment]
Hi, 

You missed the Out.rf.ref_complexes.txt file. Did you see EPIC calculate correlation scores for you? I suspect the reason is you haven't properly initialized the computation by using the wrong directory.

When you run EPIC, check https://github.com/BaderLab/EPIC/blob/master/EPIC-Manual.pdf, especially pay attention to the red words in the step 5 of Starting EPIC. You need to cd to the directory containing the input folder.

Have a try, let me know if this solves ur problem.

Best
Lucas
